### ISSUE TITLE
rouge-calculate

### ISSUE THREAD

**Issue by zhipeng-cai** [soarsmu/PRTiger#1]
hello, did you calculate the rouge metric with this 'datasets' package in your paper?
print('using datasets...')
    use_datasets(generated_summaries, reference_summaries)

**Comment by happygirlzt** [comment]
Hi, you need to pass the arguments `target` and `predict` when running https://github.com/soarsmu/PRTiger/blob/main/src/calculate_rouge.py
an example:

```bash
python calculate_rouge.py --target ground_truth.txt --predict predict.txt
```

**Comment by happygirlzt** [comment]
Yes, we used the `datasets` package.

**Comment by zhipeng-cai** [comment]
> Yes, we used the `datasets` package.

okk，thank you!!!

**Comment by happygirlzt** [comment]
You're welcome :)
